site_name: reghdfe
pages:
- [index.md, Home]
- [install.md, Installation]
- [guide.md, User Guide]
- [examples.md, Examples]
- [syntax.md, Detailed Syntax]
- [warnings.md, Warnings]
- [technical_notes.md, Technical Notes]
- [author.md, Author]
theme: readthedocs