site_name: reghdfe - Linear Regressions with Fixed Effects
site_url: http://scorreia.com/reghdfe
site_description: User guide for the Stata reghdfe package
site_author: Sergio Correia

repo_url: https://github.com/sergiocorreia/reghdfe


pages:
- [index.md, Home]
- [install.md, Installation]
- [reghdfe.html, Stata Help for reghdfe]
- [hdfe.html, Stata Help for hdfe]
- [guide.md, User Guide]
- [examples.md, Examples]
- [syntax.md, Detailed Syntax]
- [warnings.md, Warnings]
- [technical_notes.md, Technical Notes]
- [author.md, Author]

theme: readthedocs
copyright: Copyright &copy; 2015, <a href="http://scorreia.com">Sergio Correia</a>.
google_analytics: ['UA-56468515-1', 'mkdocs.org']